version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    depends_on:
      - frontend
    command: python manage.py runserver 0.0.0.0:8000
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    command: npm run dev